### PR TITLE
rename twitter to twitter/x

### PR DESCRIPTION
**Pull request by Aholicknight**
Attempt 2 to rename "twitter" to "twitter/x" in list of supported services

If I am missing any files that I need to rename, please comment. I was going to edit [service-allias.js](https://github.com/wukko/cobalt/blob/main/api/src/processing/service-alias.js)

### CODE REVIEW

**Comment by yeeterlol** [comment]
keep it twitter

**Comment by user1126s** [comment]
twitter = yay
twitter/x = hmmm
x = nooo

**Comment by MMJv3** [comment]
boooooo useless QOL change x is a dumb name

**Comment by Aholicknight** [comment]
> boooooo useless QOL change x is a dumb name

blame "X" not me

**Comment by wukko** [comment]
we're keeping it "twitter"

also, you can't put "/" into filenames

**Pull request closed without merging**
