### PR TITLE
tests: fix broken twitter links

### PR DESCRIPTION
**Pull request by hyperdefined**
This fixes 2 of the Twitter links. 
* `TwitterSpaces` account is now `XSpaces`, was failing the test before. Renaming fixes it.
* The `Twitter` account is private, so the mixed media test was failing. This replaces it with a random tweet I found that has a photo, video, and gif.

### CODE REVIEW

**Comment by ihatespawn** [comment]
> TwitterSpaces account is now XSpaces, was failing the test before.

It normally redirects so it shouldn't be a problem

**Comment by hyperdefined** [comment]
> > TwitterSpaces account is now XSpaces, was failing the test before.
> 
> It normally redirects so it shouldn't be a problem

Correct, but cobalt doesn't follow the redirect, and it fails. Try the tweet: `https://twitter.com/TwitterSpaces/status/1526955853743546372` it will fail.

**Comment by wukko** [comment]
cobalt only uses the tweet id

**Comment by dumbmoron** [comment]
> Correct, but cobalt doesn't follow the redirect, and it fails. Try the tweet: `https://twitter.com/TwitterSpaces/status/1526955853743546372` it will fail.

it fails because the link got marked as nsfw for some reason?

anyways i think it should be replaced with something that works even if you are logged out

**Comment by hyperdefined** [comment]
I used a different video, this one should work in theory.

**Review by dumbmoron — APPROVED** [review]

**Pull request merged**
